spring:
  config:
    import: optional:file:./external-credentials.yml
  cloud:
    azure:
      active-directory:
        # Yml structure Learn doc link : https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide?tabs=SpringCloudAzure4x
        enabled: true
        profile:
          # Specifies your Active Directory ID:
          tenant-id: 05b517cb-91be-4aab-b00d-c52953bdafae
        credential:  
          # client-id and client-secret will be imported from external-credentials.yml
        # Specifies the post-log-out-redirect-uri, where to return your app after logout.
        post-logout-redirect-uri: http://localhost:8080
        # Specifies the Microsoft Graph scopes that your app needs access to - not required in this app.
        # authorization-clients:
        #   graph:
        #     scopes: https://graph.microsoft.com/User.Read

# which routes to restrict to authenticated users only (see SecurityConfig.java):
# enter String array (comma-separated) or just one route.
# e.g. authenticated: /route1, /route2, /route3
app:
  protect:
    authenticated: /token_details

# un-comment the following lines if you are deploying to a reverse proxy (e.g. Azure App Service)
# server:
#   forward-headers-strategy: native
#   tomcat:
#     remoteip:
#       protocol-header: "X-Forwarded-Proto"
#       remote-ip-header: "X-Forwarded-For"
#       internal-proxies: ".*"
